// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccountID struct {
	ID int `json:"id"`
}

type NewAccount struct {
	Name                string  `json:"name"`
	Industry            *string `json:"industry"`
	Description         *string `json:"description"`
	Tier                *int    `json:"tier"`
	URL                 *string `json:"url"`
	HeadcountUpperBound *int    `json:"headcountUpperBound"`
	HeadcountLowerBound *int    `json:"headcountLowerBound"`
	RevenueUpperBound   *int    `json:"revenueUpperBound"`
	RevenueLowerBound   *int    `json:"revenueLowerBound"`
}

type NewContact struct {
	FirstName string     `json:"firstName"`
	LastName  string     `json:"lastName"`
	State     *string    `json:"state"`
	Account   *AccountID `json:"account"`
	JobTitle  *string    `json:"jobTitle"`
	Seniority *string    `json:"seniority"`
	Persona   *string    `json:"persona"`
	Email     *string    `json:"email"`
	Phone     *string    `json:"phone"`
}

type NewContactAssignmentEntry struct {
	ContactID  string `json:"contactId"`
	AssignedBy string `json:"assignedBy"`
	AssignedTo string `json:"assignedTo"`
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewWorkspace struct {
	Name string `json:"name"`
}

type UserID struct {
	ID int `json:"id"`
}
